### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by qxu1994** [lushan88a/google_trans_new#13]
Hi!

I was trying to get Spanish translations of English words. For example:
        translator = google_translator()  
        translator.translate('children',lang_tgt='es')

But I got a TypeError: 'NoneType' object is not iterable

I manually checked the ones that didn't work. It seems that all of their Spanish translations have two forms, a feminine form and a masculine form. 

If that is the reason, is it possible to return both forms?

Thanks!

**Comment by lushan88a** [comment]
This problem is real good！
Thanks for the problem！
I will solve this problem as soon as possible ：）

**Comment by lushan88a** [comment]
I have fix this problem.
You can try it. ：）

**Comment by qxu1994** [comment]
It works perfectly well now. Thanks a lot!
