### ISSUE TITLE
is it unlimited characters supported?

### ISSUE THREAD

**Issue by noman00910** [lushan88a/google_trans_new#2]
Hi, is this library is forked from googletrans? .... 
I am asking because that library sometimes does not support bulk requests from same IP. 
I want to know if this library supports bulk queries.

**Comment by lushan88a** [comment]
It's not the forked from googletrans. You mean is the googletrans  sometimes does not support bulk requests from same IP? I found this problem too, so i make this library.
This library does not support bulk requests temporarily, I will add this function as soon as possible.
Please tell me If you found some problem when you use this library.
Thanks.
