### ISSUE TITLE
google_new_transError: Failed to connect. Probable cause: timeout

### ISSUE THREAD

**Issue by okkymabruri** [lushan88a/google_trans_new#27]
Hi @lushan88a , google_trans_new is great. I've used it a few days ago. I tried today but I have an error. 

My purpose is to translate from id to en
```
from google_trans_new import google_translator

translator = google_translator()

df["desc"] = df["uraian"].apply(translator.translate, lang_tgt="en")
df
```
The error
![image](https://user-images.githubusercontent.com/57498478/104873062-341f0200-5982-11eb-9f81-2d519739818a.png)
![image](https://user-images.githubusercontent.com/57498478/104873088-4600a500-5982-11eb-939c-051efe0d6295.png)
![image](https://user-images.githubusercontent.com/57498478/104873161-73e5e980-5982-11eb-8638-21449e2ec554.png)
![image](https://user-images.githubusercontent.com/57498478/104873201-8d873100-5982-11eb-9ee4-6d3d1bd23f3e.png)

**Comment by jmagdeska** [comment]
I'm facing the same error

**Comment by brendachirata** [comment]
hello guys @okkymabruri @jmagdeska . Did you manage to find a solution for this? im facing the same problem now, TIA

**Comment by okkymabruri** [comment]
@jmagdeska @brendachirata 
I move to https://github.com/Saravananslb/py-googletranslation. This one is my recommendation.

**Comment by brendachirata** [comment]
Thank you very much. I will let you know how it works for me.
