### ISSUE TITLE
Translation Limit per day and usage of Proxy with request

### ISSUE THREAD

**Issue by mohamedniyaz1996** [lushan88a/google_trans_new#3]
Is there any limit per day/week/month for using this API? Because at google_trans there is a way to specify proxy wich is not possible here it seems.

Actually in a nutshell , need to know , whether this will get blocked by Google , if I put around 10k-20k strings (containing 3-5 words) per day.

If this new one handles proxies internally , happy to use this :).

**Comment by lushan88a** [comment]
So far, this api has not been restricted.



发自我的iPhone


------------------ Original ------------------

**Comment by mohamedniyaz1996** [comment]
Ok, let me test this with 10k short string and will get back, Thanks a lot for replying.

**Comment by lushan88a** [comment]
Please tell me if you have any error when you use this library
Thanks!

**Comment by mohamedniyaz1996** [comment]
@lushan88a , please give me 2 more days , Will need to test for stability as well.

**Comment by lushan88a** [comment]
I have fix this problem. You can try the new version :)

**Comment by mohamedniyaz1996** [comment]
Till now , I had done translation for 10K Strings, no block faced till now.

Let me know if I can contribute something to this API further.
