### ISSUE TITLE
Consider adding a simple example at https://github.com/lushan88a/google_trans_new#translate

### ISSUE THREAD

**Issue by fawazahmed0** [lushan88a/google_trans_new#4]
For example something like this:

```python

from google_trans_new import google_translator  
  
translator = google_translator()  
translate_text = translator.translate('สวัสดีจีน',lang_tgt='en',lang_src='th' )  
# <Translate text=สวัสดีจีน lang_tgt=th lang_src=en>  
#  default parameter : lang_src=auto lang_tgt=auto 
#  API can automatically identify the src translation language, so you don’t need to set lang_src
print(translate_text)

```

Why am I saying this?
The user will first copy and paste the code in python IDE,to see if it runs fine , the [example](https://github.com/lushan88a/google_trans_new#translate) will break because of proxies.

You can specify url_suffix ,proxies etc example after basic example.

Thanks

**Comment by Johnne32** [comment]
> 
> 
> For example something like this:
> 
> ```python
> from google_trans_new import google_translator  
>   
> translator = google_translator()  
> translate_text = translator.translate('สวัสดีจีน',lang_tgt='en',lang_src='th' )  
> # <Translate text=สวัสดีจีน lang_tgt=th lang_src=en>  
> #  default parameter : lang_src=auto lang_tgt=auto 
> #  API can automatically identify the src translation language, so you don’t need to set lang_src
> print(translate_text)
> ```
> 
> Why am I saying this?
> The user will first copy and paste the code in python IDE,to see if it runs fine , the [example](https://github.com/lushan88a/google_trans_new#translate) will break because of proxies.
> 
> You can specify url_suffix ,proxies etc example after basic example.
> 
> Thanks
Thanks Fawaz for leading me here. I just tested it and it worked. No more limits

**Comment by fawazahmed0** [comment]
> 
> 
> > For example something like this:
> > ```python
> > from google_trans_new import google_translator  
> >   
> > translator = google_translator()  
> > translate_text = translator.translate('สวัสดีจีน',lang_tgt='en',lang_src='th' )  
> > # <Translate text=สวัสดีจีน lang_tgt=th lang_src=en>  
> > #  default parameter : lang_src=auto lang_tgt=auto 
> > #  API can automatically identify the src translation language, so you don’t need to set lang_src
> > print(translate_text)
> > ```
> > 
> > 
> > Why am I saying this?
> > The user will first copy and paste the code in python IDE,to see if it runs fine , the [example](https://github.com/lushan88a/google_trans_new#translate) will break because of proxies.
> > You can specify url_suffix ,proxies etc example after basic example.
> > Thanks
> 
> Thanks Fawaz for leading me here. I just tested it and it worked. No more limits

welcome mate

**Comment by lushan88a** [comment]
> For example something like this:
> 
> ```python
> from google_trans_new import google_translator  
>   
> translator = google_translator()  
> translate_text = translator.translate('สวัสดีจีน',lang_tgt='en',lang_src='th' )  
> # <Translate text=สวัสดีจีน lang_tgt=th lang_src=en>  
> #  default parameter : lang_src=auto lang_tgt=auto 
> #  API can automatically identify the src translation language, so you don’t need to set lang_src
> print(translate_text)
> ```
> 
> Why am I saying this?
> The user will first copy and paste the code in python IDE,to see if it runs fine , the [example](https://github.com/lushan88a/google_trans_new#translate) will break because of proxies.
> 
> You can specify url_suffix ,proxies etc example after basic example.
> 
> Thanks

Thanks for your proposal！ ：)

**Comment by fawazahmed0** [comment]
> 
> 
> > For example something like this:
> > ```python
> > from google_trans_new import google_translator  
> >   
> > translator = google_translator()  
> > translate_text = translator.translate('สวัสดีจีน',lang_tgt='en',lang_src='th' )  
> > # <Translate text=สวัสดีจีน lang_tgt=th lang_src=en>  
> > #  default parameter : lang_src=auto lang_tgt=auto 
> > #  API can automatically identify the src translation language, so you don’t need to set lang_src
> > print(translate_text)
> > ```
> > 
> > 
> > Why am I saying this?
> > The user will first copy and paste the code in python IDE,to see if it runs fine , the [example](https://github.com/lushan88a/google_trans_new#translate) will break because of proxies.
> > You can specify url_suffix ,proxies etc example after basic example.
> > Thanks
> 
> Thanks for your proposal！ ：)

Thanks for adding a simple basic example :)
